import Head from 'next/head';
import { useAuthState } from 'react-firebase-hooks/auth';
import { useRouter } from 'next/router';
import { auth } from '../firebase/auth';
import 'firebase/firestore';
import { useContext } from 'react';
import { AppContext } from '../AppState';

export default function Home() {
    const { user, isUserLoading } = useContext(AppContext);
    const router = useRouter();

    if (isUserLoading) {
        return <div>Loading...</div>;
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className='w-full overflow-auto'>
                <div>Home page</div>
            </main>
        </>
    );
}
