import Head from 'next/head';
import { useAuthState } from 'react-firebase-hooks/auth';
import { useRouter } from 'next/router';
import { auth } from '../firebase/auth';
import getAlbums from '../firebase/getAlbums';
import { useState } from 'react';
import 'firebase/firestore';

export default function Home() {
  const [albums, setAlbums] = useState(null);
  const router = useRouter();
  const [user, loading] = useAuthState(auth);

  getAlbums.then((data) => {
    setAlbums(data);
  });

  console.log(albums);

  if (loading) {
    return <div>Loading...</div>;
  }

  if (!user) {
    router.push('/login');
  }

  console.log(user);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='w-full overflow-auto'>
        <div>
          {albums?.map((album) => {
            return (
              <div className='' key={album.id}>
                {album.name}
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
}
